column_dtypes:
    date_cols:
      - date_recorded  # 2010-09-23
      - construction_year  # e.g. 1960

    float_cols:
      - amount_tsh
      - longitude
      - latitude

    int_cols:
      - gps_height
      - num_private
      - region_code
      - district_code
      - population

    str_cols:
      - funder
      - installer
      - wpt_name
      - basin
      - subvillage
      - region
      - lga
      - ward
      - public_meeting  # boolean
      - scheme_management
      - scheme_name
      - permit
      - extraction_type
      - extraction_type_group
      - extraction_type_class
      - management
      - management_group
      - payment
      - payment_type
      - water_quality
      - quality_group
      - quantity
      - quantity_group
      - source
      - source_type
      - source_class
      - waterpoint_type
      - waterpoint_type_group

    remove_cols:
      - recorded_by  # Constant, no variation
  
  